### ISSUE TITLE
Verbesserung Loginverfahren

### ISSUE THREAD

**Issue by rhyperio** [mohjohfox/cli-sudoku#11]
**Description**
Verbessere das Loginverfahren um dem Benutzer Feedback zu geben, was während des Loginvorgangs fehlerhaft war. Es soll nicht notwendig sein, nochmal gefragt zu werden ob bereits eine Registrierung vor liegt.

**Subtasks**
- [ ] Implementierung
- [ ] SuccessfulLogin Variable immer true, daher entfernen

**Acceptance Criteria**
- [ ] Benutzer erhält Feedback bei fehlerhaftem Login
- [ ] Bei fehlerhaftem Login direkte, neue Loginchance
- [ ] Benutzer kann Loginvorgang abbrechen und zum Registrierungsbildschirm zurückkehren

**Comment by whole01** [comment]
Wie soll das Abbrechen implementiert werden? Wenn nach einem gescheiterten Login Versuch gefragt wird, gibt es wieder keine direkte neue Loginchance.

**Comment by whole01** [comment]
SuccesfulLogin Variable in neuem Pull-Request entfernt.
Dialog bei fehlerhaftem login und neue Loginchance bereits implementiert.
