### ISSUE TITLE
Anmeldemaske bei Start der Anwendung

### ISSUE THREAD

**Issue by mohjohfox** [mohjohfox/cli-sudoku#2]
**Subtasks**
- [x] Speichern eines neuen Nutzers mit Nutzername und Passwort
- [x] Prüfen des Passworts beim Anmelden

**Acceptance Criteria**
- [ ] Passwort wird geprüft bei Anmeldung
- [ ] Keine doppelten Nutzernamen erlaubt
