### ISSUE TITLE
Ändern der Ausführungsreihenfolge

### ISSUE THREAD

**Issue by rhyperio** [mohjohfox/cli-sudoku#21]
**Description**
Aktuell wird nach dem beenden des Programms (Logout und Ablehnen des erneuten logins) die Abfrage nach dem Schwierigkeitsgrad durchgeführt.
Die Ausführungsreihenfolge, vor allem in der Main Methode soll angepasst werden.
Die Auswahl des Schwierigkeitsgrades soll erst nach Auswahl der Option "Play" möglich sein.

**Story Points: 0** 

**Subtasks**
- [x] Entfernen der Schwierigkeitslogik aus der Klasse Main
- [x] Anpassen der Aufrufe nach dem Treffen einer Auswahl im Menü

**Acceptance Criteria**
- [x] In der Main Klasse wird keine Schwierigkeit mehr ausgegeben nach Logout und dem Wunsch, sich nicht wieder einzuloggen
- [x] Nach Auswahl des Menüpunktes "Play" wird die Auswahl des Schwierigkeitsgrades angezeigt

**Additional context**
