### ISSUE TITLE
Zeitstoppen während der Bearbeitung

### ISSUE THREAD

**Issue by rhyperio** [mohjohfox/cli-sudoku#27]
**Description**
Dem Nutzer soll es ermöglicht werden die Zeit zu stoppen, während der Bearbeitung eines Sudokus.
Die Zeit, welche der Benutzer für das Lösen des Sudokus braucht, kann unter anderem für die Bestenliste verwendet werden.

**Story Points: 0** 

**Subtasks**
- [ ] Zeitstoppen implementieren
- [ ] Abspeichern der Zeit anhand von Benutzername
- [ ] Laden der Zeit implementieren

**Acceptance Criteria**
- [ ] Die Zeit wird korrekt gestoppt
- [ ] Die Zeit wird abgespeichert
- [ ] Die Zeit kann geladen werden
