### ISSUE TITLE
Zwischenspeichern und Laden von Sudokus ermöglichen

### ISSUE THREAD

**Issue by rhyperio** [mohjohfox/cli-sudoku#29]
**Description**
Während der Bearbeitung eines Sudokus soll das Sudoku gespeichert werden können, damit es später weiter bearbeitet werden kann. Im Hauptmenu soll es einen Menupunkt zum spielen von gespeicherten Sudokus geben. Aus der Liste der gespeicherten Sudokus soll eins ausgewählt werden.
Außerdem muss es möglich sein, die Bearbeitung eines Sudokus auch ohne Speichern abzubrechen.

**Subtasks**
- [ ] Sudoku spielen abbrechen
- [ ] Sudoku während des Spielens speichern und zum Hauptmenu zurückkehren
- [ ] Gespeicherte Sudokus spielen übers Hauptmenu starten

**Acceptance Criteria**
- [ ] Play Dialog um, bestehende Sudokus erweitern
- [ ] Hauptmenu um neuen Menupunkt erweitern
- [ ] Abbrechen von Sudokuspielen funktioniert
