### ISSUE TITLE
Anzeige Startmenu

### ISSUE THREAD

**Issue by mohjohfox** [mohjohfox/cli-sudoku#3]
**Subtasks**
- [x] Auflistung der Auswahloptionen
- [x] Weiterleitung an entsprechende Option

**Acceptance Criteria**
- [x] Folgende Optionen sind aufgelistet (vereinfacht): Spielen, Bestenliste
- [x] Weiterleitung an entsprechende Auswahlfunktion funktioniert

**Comment by rhyperio** [comment]
Bisherige Auswahlmöglichkeiten:
- Spielen
- Bestenliste
- Logout
