### ISSUE TITLE
Implementierung einer Sudoku-Datenstruktur

### ISSUE THREAD

**Issue by mohjohfox** [mohjohfox/cli-sudoku#4]
**Subtasks**
- [x] Anlegen einer Sudokuklasse
- [x] SudokuId
- [x] Speicher Sudokufeld ab -> sollte eher in einen Service
- [x] Gibt das Sudokufeld zurück
- [x] Eingabe in ein spezifisches Feld -> Sollte in einem Service gemacht werden.

**Acceptance Criteria**
- [ ] Sudokuklasse mit grundlegenden Funktionen ist angelegt
