### ISSUE TITLE
Sudokugenerierung

### ISSUE THREAD

**Issue by mohjohfox** [mohjohfox/cli-sudoku#6]
**Subtasks**
- [ ] Sudokuklasse um benötigte Funktionen erweitern
- [ ] Sudoku passend für Schwierigkeitsgrad generieren

**Acceptance Criteria**
- [ ] Sudokus werden passend für Schwierigkeitsgrad generiert
- [ ] Sudokus sind immer unterschiedlich

**Comment by whole01** [comment]
Es gibt verschiedene Möglichkeiten Sudokus zu generieren. Da wir noch viel Code gebrauchen können ist auch eine Idee, verschiedene Methoden zu implementieren.

Die Generierung sollte dann in einer separaten Klasse stattfinden und nicht in der Sudokuklasse.

**Comment by mohjohfox** [comment]
Mögliche Wege, ein Sudoku zu erstellen: https://de.wikipedia.org/wiki/Sudoku#Erstellung_neuer_Sudokus

**Comment by mohjohfox** [comment]
Ich schaue mir die Generierung mittels Sudoku Solver an (Weg 1) aus dem Wiki-Artikel. Hierzu wird allerdings ein Sudoku-Solver benötigt, welcher in der Issue #9 beschrieben ist. Daher setzte ich zuerst den Solver aus Issue #9 um.

**Comment by whole01** [comment]
Ich würde mir die Generierung über Transformation anschauen (Weg 3 aus dem Wiki-Artikel).

**Comment by rhyperio** [comment]
Ist der Plan, alle fünf Wege zu implementieren? Und später wenn wir eine Generierung und den geplanten Solver implementiert haben können wir ja auch noch den Ansatz nehmen, wo über ein bereits gelöstes Sudoku eins erstellt wird.
Oder war die ganze Thematik anders angedacht?

**Comment by mohjohfox** [comment]
> 

Würde jetzt nicht sagen, dass wir alle fünf Wege implementieren müssen. Würde es je nach Bedarf und wie gut die einzelnen Implementierungen sind entscheiden oder?

**Comment by whole01** [comment]
Denke auch, dass alle Wege nicht nötig sind. Wenn am Schluss noch viel fehlt kann man ja noch mit denen auffüllen. Wenn schon eine Implementierung angefangen wurde, kann man ja trotzdem weiter machen.
