### ISSUE TITLE
Anzeigefunktion (Parser) von Sudokus

### ISSUE THREAD

**Issue by mohjohfox** [mohjohfox/cli-sudoku#7]
**Subtasks**
- [x] Sudoku in bekannter Ansicht ausgeben
- [ ] Terminal "aufräumen"

**Acceptance Criteria**
- [ ] Sudoku wird in bekannter ansicht ausgegeben
- [ ] Sudoku wird in einem leeren Terminal ausgegeben
