### ISSUE TITLE
Eingabemechanismus zum Ausfüllen eines Sudokus

### ISSUE THREAD

**Issue by mohjohfox** [mohjohfox/cli-sudoku#8]
**Subtasks**
- [ ] Werte in Sudoku eintragen
- [ ] Erneute Ausgabe des Spielfeldes

**Acceptance Criteria**
- [ ] Werte sind im Sudokufeld hinterlegt
- [ ] Aktualisiertes Spielfeld wird ausgegeben
