### ISSUE TITLE
Aktuelles Suduko validieren

### ISSUE THREAD

**Issue by mohjohfox** [mohjohfox/cli-sudoku#9]
**Subtasks**
- [ ] Sudoku Validierung ermöglichen
- [ ] Sudoku im Play Dialog bei komplett ausgefülltem Feld validieren und Rückmeldung dem Spieler melden

**Acceptance Criteria**
- [ ] Aktuelles Sudoku kann validiert werden
